# Generated by Django 5.2 on 2025-04-07 10:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '.category_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoryGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='Products.categorygroup')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_off', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='product-image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Products.category')),
                ('product_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productbrand')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('W28', 'Waist 28'), ('W30', 'Waist 30'), ('W32', 'Waist 32'), ('W34', 'Waist 34'), ('W36', 'Waist 36'), ('W38', 'Waist 38'), ('W40', 'Waist 40'), ('W42', 'Waist 42'), ('D2', 'Size 2'), ('D4', 'Size 4'), ('D6', 'Size 6'), ('D8', 'Size 8'), ('D10', 'Size 10'), ('D12', 'Size 12'), ('D14', 'Size 14'), ('D16', 'Size 16'), ('EU36', 'EU 36'), ('EU37', 'EU 37'), ('EU38', 'EU 38'), ('EU39', 'EU 39'), ('EU40', 'EU 40'), ('US6', 'US 6'), ('US7', 'US 7'), ('US8', 'US 8'), ('US9', 'US 9'), ('UK5', 'UK 5'), ('UK6', 'UK 6'), ('UK7', 'UK 7'), ('UK8', 'UK 8')], max_length=5)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='Products.product')),
            ],
            options={
                'db_table': 'size',
            },
        ),
    ]
