# Generated by Django 5.2 on 2025-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_brand', to='Products.productbrand'),
        ),
    ]
