# Generated by Django 5.2 on 2025-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_product_brand_product_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('Free', 'Free'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large'), ('W28', 'Waist 28'), ('W30', 'Waist 30'), ('W32', 'Waist 32'), ('W34', 'Waist 34'), ('W36', 'Waist 36'), ('W38', 'Waist 38'), ('W40', 'Waist 40'), ('W42', 'Waist 42'), ('D2', 'Size 2'), ('D4', 'Size 4'), ('D6', 'Size 6'), ('D8', 'Size 8'), ('D10', 'Size 10'), ('D12', 'Size 12'), ('D14', 'Size 14'), ('D16', 'Size 16'), ('EU36', 'EU 36'), ('EU37', 'EU 37'), ('EU38', 'EU 38'), ('EU39', 'EU 39'), ('EU40', 'EU 40'), ('US6', 'US 6'), ('US7', 'US 7'), ('US8', 'US 8'), ('US9', 'US 9'), ('UK5', 'UK 5'), ('UK6', 'UK 6'), ('UK7', 'UK 7'), ('UK8', 'UK 8')], max_length=5),
        ),
    ]
