# Generated by Django 5.2 on 2025-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
