# Generated by Django 5.2 on 2025-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_alter_customeruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
